language: node_js
node_js:
  - "6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - libusb-1.0-0-dev
    - libudev-dev

script:
  - npm run lint
  - npm run build
  - npm test

deploy:
  provider: npm
  email: chris@hichris.com
  api_key:
    secure: epQbbT7MKLaa/1UHuxQvLjdWjz7PGgzfTUVpaShd1/XsQVLZPrVyfahNZAbf9LJ303SF+P1MyQMTfRLF5ViP/wTeYuA0DcCTjJC0TfmQxAZ8VtUtWxJqnAx9l6HV3HkiFdEtRQRkBYZi5TKMik5Q3N6Gz2068ShMD/bFamrLNF55Xnv2xy1RTVdjZGXCjRv8I89PxKwXo2YZDLmxrcxHF6RsXeXwW0pXtS65dC5ChbnJr+dwUIVxVdE3w934AgDup20ysVEWwfv1aQse6lhXsV+gyhqTypdRTY+vywtrif/uU3WVmwvBTbz4kemO9UJ6s9Xl9IB9wOtZzCVm2i8E4tnfUarkgRTlOo5ZST2M5yNk6StCSlUkBdELVEy+YYyIi6igsvDojQA2CL/w5M8jy9TsPpeLkO/1GRCFAQBe5yKibDpJfrQJyaGP59iPLrVjA7vDiCBXt7BaYVXaz9blb9qDKFaMPIlyp+u5qUcV+y5wTNX1OVqKK3HuaD2JHiIzRR3C41tzLp516Sw82mjRIdI1TAkaVlrnZxRCMQjcITTai43hCuu+jP+ezPGInk5QRf/HZq3UVOadNah7/OrVipw2drGmzs0k0RuJ4pTT0SOHTSiVRm08R+MBER2EuNnhL1/nOZMmP3x2uYOPXeQSrgx6CWWmzxw5lDCwQ4Cv5Go=
  on:
    branch: master
  skip_cleanup: true
